name = "TestPkg"
uuid = "6729d840-4725-4c06-943f-d975883f63e4"
authors = ["Bruno Amorim <amorim.bac@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
